CREATE TABLE TB_ESTADO (
SGESTADO INT (2) ZEROFILL NOT NULL PRIMARY KEY,
NMESTADO CHAR (2) NOT NULL
);

INSERT INTO TB_ESTADO VALUES 
('01','SP');



CREATE TABLE TB_CIDADE (
CDCIDADE INT (2) ZEROFILL AUTO_INCREMENT NOT NULL PRIMARY KEY,
NMCIDADE VARCHAR (45) NOT NULL,
SGESTADO INT (2) ZEROFILL NOT NULL,
FOREIGN KEY (SGESTADO) REFERENCES TB_ESTADO (SGESTADO)
);

INSERT INTO TB_CIDADE VALUES
(NULL,'ITANHAEM','01');


CREATE TABLE TB_BAIRRO (
CDBAIRRO INT(2) ZEROFILL AUTO_INCREMENT NOT NULL PRIMARY KEY,
NMBAIRRO VARCHAR (45) NOT NULL,
CDCIDADE INT(2) ZEROFILL  NOT NULL,
FOREIGN KEY (CDCIDADE) REFERENCES TB_CIDADE (CDCIDADE)
);
select * FROM TB_BAIRRO;
INSERT INTO TB_BAIRRO VALUES
(NULL,'LOTY','01'),
(NULL,'CENTRO','01'),
(NULL,'SAVOY','01'),
(NULL,'GRANDESP','01'),
(NULL,'OASIS','01'),
(NULL,'BELAS ARTES','01'),
(NULL,'GUAPIRANGA','01'),
(NULL,'SUARAO','01'),
(NULL,'GAIVOTA','01');

CREATE TABLE TB_ADMIN (
    CDADMIN INT (02) ZEROFILL NOT NULL PRIMARY KEY,
    NMADMIN VARCHAR (100) NOT NULL,
    CPF VARCHAR (11) NOT NULL,
    SENHA VARCHAR (50) NOT NULL,
    NIVEL ENUM ('1','2') NOT NULL DEFAULT '1'
);

INSERT INTO TB_ADMIN VALUES
('01', 'MATHEUS','12312312344','admin','1');

CREATE TABLE TB_POSTO (
CDPOSTO INT(2) ZEROFILL AUTO_INCREMENT NOT NULL PRIMARY KEY,
NMPOSTO VARCHAR(45) NOT NULL,
TELEFONE1 BIGINT NOT NULL,
TELEFONE2 BIGINT,
ENDERECO VARCHAR (200) NOT NULL,
EMAIL VARCHAR (200) NOT NULL,
CDBAIRRO INT (2) ZEROFILL NOT NULL,
CDADMIN INT (2) ZEROFILL,
FOREIGN KEY (CDBAIRRO) REFERENCES TB_BAIRRO (CDBAIRRO)
);

INSERT INTO TB_POSTO VALUES
('01','USFLOTY','1334243279',NULL,'ALAMEDA GUARAÇAI, S/N','usf@loty.sp.gov.br','01','01'),
('02','USFSAVOY','1334261798',NULL,'R. JAIME LINO DOS SANTOS, 290','usf@savoy.sp.gov.br','03','01'),
('03','USFGUAPIRANGA','1334265807',NULL,'RUA VEREADOR JOAO BECHIR, 114-132','usf@guapiranga.sp.gov.br','07','01'),
('04','USFCENTRO','1334264685',NULL,'AV. TIRADENTES, 97','usf@centro.sp.gov.br','02','01'),
('05','USFGRANDESP','1334253375',NULL,'AV. ALEMANHA, 106','usf@grandesp.sp.gov.br','04','01'),
('06','USFSUARAO','1334261577',NULL,'R. PADRE AFONSO MARIA RATISBONE, 921','usf@suarao.sp.gov.br','08','01'),
('07','USFOASIS','1334277533',NULL,'R. ESTANISLEU GERONIMO, 418','usf@oasis.sp.gov.br','05','01'),
('08','USFBELASARTES','1334261402',NULL,'R. ANA MARIA MARTINS RIVERA, 10','usf@belasartes.sp.gov.br','06','01'),
('09','USFGAIVOTA','1334291410',NULL,'AV. FLACIDES FERREIRA, 500','usf@gaivota.sp.gov.br','09','01');




CREATE TABLE TB_VACINA (
CDVACINA INT(2) ZEROFILL PRIMARY KEY NOT NULL,
NMVACINA VARCHAR(120) NOT NULL,
FABRICANTE VARCHAR (120) NOT NULL
);

INSERT INTO TB_VACINA VALUES
('01','CORONAVAC','SINOVAC/BUTANTAN'),
('02','ASTRAZENECA','OXFORD/FIOCRUZ'),
('03','PFIZER','PFIZER/BIONTECH'),
('04','JANSSEN','JANSSEN-CILAG'),
('05','SPUTNIK','GAMALEYA'),
('06','COVAXIN','BHARAT BIOTECH');

CREATE TABLE ESTOQUE_VAC (
CDMEDICAMENTO INT(3) ZEROFILL NOT NULL PRIMARY KEY,
DTFAB DATE NOT NULL,
DTVAL DATE NOT NULL,
LOTE VARCHAR (55) NOT NULL,
QNTVAC BIGINT NOT NULL,
TEXTVAC VARCHAR (355) NOT NULL,
CATEGVAC VARCHAR (255) NOT NULL,
CDPOSTO INT (2) ZEROFILL NOT NULL,
CDVACINA INT(2) ZEROFILL,
FOREIGN KEY (CDVACINA) REFERENCES TB_VACINA (CDVACINA),
FOREIGN KEY (CDPOSTO) REFERENCES TB_POSTO (CDPOSTO)
);

INSERT INTO ESTOQUE_VAC VALUES
('01','2021-01-21','2021-12-30','12345','500','APLICACAO EM DUAS DOSES, SENDO A SEGUNDA ENTRE 14 E 28 DIAS.'
,'CRIANCAS,JOVENS E ADULTOS','02','01');

CREATE TABLE TB_PACIENTE (
CDPACIENTE INT(2) ZEROFILL  AUTO_INCREMENT NOT NULL PRIMARY KEY,
EMAIL VARCHAR (255) NOT NULL,
SENHA VARCHAR(55) NOT NULL,
TELEFONE VARCHAR(11) NOT NULL,
TELEFONE2 VARCHAR(11),
SEXO ENUM ('M', 'F') NOT NULL,
NOME VARCHAR (255) NOT NULL,
ENDERECO VARCHAR (255) NOT NULL,
TPSANG CHAR (3) NOT NULL,
RG VARCHAR(11) NOT NULL,
CPF VARCHAR(11) NOT NULL,
DTNASC DATE NOT NULL,
CDPOSTO INT (2) ZEROFILL NOT NULL,
ATIVO BOOL NOT NULL DEFAULT '1',
FOREIGN KEY (CDPOSTO) REFERENCES TB_POSTO (CDPOSTO)
);

INSERT INTO TB_PACIENTE VALUES
('01', 'paciente@email.com', 'Paciente_123', '13988776655', null, 'M', 'Paciente da silva', 'RUA JOSE MARIANO ALVES, 3344', 
'A-', '112223334','11122233344','1995-01-21','03','1');


SELECT * FROM TB_PACIENTE;

CREATE TABLE TB_CARTEIRA (
CDCARTEIRA INT(2) ZEROFILL AUTO_INCREMENT NOT NULL PRIMARY KEY,
CDVACINA INT (2) ZEROFILL NOT NULL,
DT_VAC_APLIC DATE NOT NULL,
DT_PROX_DOSE DATE,
CDPOSTO INT (2) ZEROFILL NOT NULL,

FK_PACIENTE INT (2) ZEROFILL,
FOREIGN KEY (CDPACIENTE) REFERENCES TB_PACIENTE (CDPACIENTE),

FOREIGN KEY (CDVACINA) REFERENCES TB_VACINA (CDVACINA),
FOREIGN KEY (CDPOSTO) REFERENCES TB_POSTO (CDPOSTO)
);

INSERT INTO TB_CARTEIRA VALUES
('01','01','2022-01-05',NULL,'01');
