


CREATE TABLE TB_ESTADO (
SGESTADO CHAR (2) NOT NULL PRIMARY KEY,
NMESTADO VARCHAR (45) NOT NULL
);


CREATE TABLE TB_CIDADE (
CDCIDADE INT PRIMARY KEY NOT NULL,
NMCIDADE VARCHAR (45) NOT NULL,
SGESTADO CHAR (2) NOT NULL,
FOREIGN KEY (SGESTADO) REFERENCES TB_ESTADO (SGESTADO)
);

CREATE TABLE TB_BAIRRO (
CDBAIRRO INT PRIMARY KEY NOT NULL,
NMBAIRRO VARCHAR (45) NOT NULL,
CDCIDADE INT NOT NULL,
FOREIGN KEY (CDCIDADE) REFERENCES TB_CIDADE (CDCIDADE)
);

CREATE TABLE TB_ADM (
CDADM INT PRIMARY KEY NOT NULL,
NMADM VARCHAR (45) NOT NULL,
CPF BIGINT NOT NULL,
EMAIL VARCHAR (45) NOT NULL,
TELEFONE BIGINT NOT NULL,
SENHA VARCHAR (45) NOT NULL
);

CREATE TABLE TB_POSTO (
CDPOSTO INT PRIMARY KEY NOT NULL,
NMPOSTO VARCHAR(45) NOT NULL,
CNPJ BIGINT NOT NULL,
TELEFONE1 BIGINT NOT NULL,
TELEFONE2 BIGINT,
ENDERECO VARCHAR (45) NOT NULL,
EMAIL VARCHAR (45) NOT NULL,
CDBAIRRO INT NOT NULL,
CDADM INT NOT NULL,
FOREIGN KEY (CDBAIRRO) REFERENCES TB_BAIRRO (CDBAIRRO),
FOREIGN KEY (CDADM) REFERENCES TB_ADM (CDADM)
);

CREATE TABLE TB_VACINA (
CDVACINA INT PRIMARY KEY NOT NULL
);

CREATE TABLE ESTOQUE_VAC (
CDVACINA INT NOT NULL,
NMVACINA VARCHAR (55) NOT NULL,
FABRICANTE VARCHAR (55) NOT NULL,
DTFAB DATE NOT NULL,
DTVAL DATE NOT NULL,
TEXTVAC VARCHAR (355) NOT NULL,
CATEGVAC VARCHAR (255) NOT NULL,
CDPOSTO INT NOT NULL,
FOREIGN KEY (CDVACINA) REFERENCES TB_VACINA (CDVACINA),
FOREIGN KEY (CDPOSTO) REFERENCES TB_POSTO (CDPOSTO)
);

CREATE TABLE TB_PACIENTE (
CDPACIENTE INT auto_increment NOT NULL,
EMAIL VARCHAR (255) NOT NULL,
SENHA INT NOT NULL,
TELEFONE BIGINT NOT NULL,
TELEFONE2 BIGINT,
SEXO CHAR (1) NOT NULL,
NOME VARCHAR (255) NOT NULL,
ENDERECO VARCHAR (255) NOT NULL,
CDCIDADE VARCHAR (255) NOT NULL,
SGESTADO CHAR (2) NOT NULL,
TPSANG CHAR (2) NOT NULL,
RG BIGINT NOT NULL,
CPF BIGINT NOT NULL,
DTNASC DATE NOT NULL,
PRIMARY KEY (CDPACIENTE)
);





CREATE TABLE TB_CARTEIRA (
CDPACIENTE INT NOT NULL,
CDVACINA INT NOT NULL,
DT_VAC_APLIC DATE NOT NULL,
DT_PROX_DOSE DATE NOT NULL,
DT_PROX_DOSE2 DATE NOT NULL,
DT_PROX_DOSE3 DATE NOT NULL
);





























